---
title: "Fig1cd_clinicalDatasets"
output: html_document
---

## R Markdown

```{r}
library(ggplot2)
paletteCMSn=c("CMS1" ="#E79E1B", 
             "CMS2"= "#0071B1", 
             "CMS3"= "#C45597",#Guinney:"#C977A4", 
              "CMS4"="#009C74",
             "NOLBL"="#d3d3d3")

## plot CMS predictions
listCMSlabs <- list("COAD"= miR_COAD_vst$CMS, 
                    "READ"=miR_READ_vst_BR$CMS.lv, 
                    "CPTAC2"=clinSupp.cptac$CMS )
for (CMSvec in c("COAD","READ","CPTAC2")) {
CMSvecN <- factor(listCMSlabs[[CMSvec]], 
                  levels=c("CMS1", "CMS2", "CMS3", "CMS4", "NOLBL"),
                  ordered = T)
CMSvecN[is.na(CMSvecN)] <- "NOLBL"

data.frame("CMS"=CMSvecN) %>% 
  ggplot(aes(x = CMS, fill = CMS )) +
  geom_bar() +
  theme_minimal() + 
  ylim(0, 110) +
  scale_fill_manual(values=c(paletteCMSn)) + #"#4F2776"
  ggtitle(paste0("CMS in ", CMSvec))
ggsave(paste0(plotDir, "CMS_input_counts_", CMSvec, "_barplots.pdf"),
       width=3,height=3)
}
```

```{r}
#### plot Stage percent ####
listCMSlabs <- list("COAD"= as.factor( sub("Stage ", "", sub("[A-C]$" , "", 
                                                clinical.coad$ajcc_pathologic_stage[ 
                                                  match(rownames(rc_vst_BR), 
                                                              clinical.coad$submitter_id)])) ), 
                    "READ"=as.factor( sub("Stage ", "", sub("[A-C]$" , "", 
                                                clinical.read$ajcc_pathologic_stage[ 
                                                  match(rownames(miR_READ_vst_BR), 
                                                              clinical.read$submitter_id)])) ),
                    "VU"=as.factor(clinVU$Stage[grep("primary_CRC",clinVU$sampleType)] ))

for (CMSvec in c("COAD","READ","VU")) {
CMSvecN <- factor(listCMSlabs[[CMSvec]],
                  levels=c("I", "II", "III", "IV", "NA"),
                  ordered = T )
CMSvecN[is.na(CMSvecN)] <- "NA"

data.frame("Stage"=CMSvecN) %>%
  #count(Stage) %>%
  #mutate(pcStage = n / sum(n) * 100) %>% 
  ggplot(aes(x = Stage, fill = Stage )) +
  geom_bar(aes(y=100*(..count..)/sum(..count..))) +
  theme_minimal() + 
  ylim(0, 60) +
  scale_fill_manual(values=c("#457464", "#6EA54B","#8491B4FF", 
                             "#2a3b8f", "#d3d3d3")) + 
  ggtitle(paste0("Stage in ", CMSvec))
ggsave(paste0(plotDir, "Fig1_Stage_input_counts_", CMSvec, "_barplots.pdf"),
       width=3,height=3)
}


```

## Including Plots

You can also embed plots, for example:

```{r}
summary(clinVU$Gender[grepl("primair CRC", clinVU$locSample)])/126*100
# female   male   NA's 
#     49     76      1 
summary(clinVU$Age[grepl("primair CRC", clinVU$locSample)])
#  Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
# 28.00   57.00   65.00   64.45   73.00   88.00       1 
summary(clinVU$Stage[grepl("primair CRC", clinVU$locSample)])/126*100
# I   II  III   IV NA's 
# 5   17   36   66    2 

```
